// import type { Metadata } from "next";
// import { Red_Hat_Display } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from '@/app/context/ThemeContext';


// const redHatDisplay = Red_Hat_Display({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"], // regular (400), medium (500), semibold (600), bold (700)
//   variable: "--font-red-hat-display", // CSS variable for tailwind/custom usage
// });

// export const metadata: Metadata = {
//   title: "Whorkaz",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${redHatDisplay.className} transition-colors duration-300`}>
//         <ThemeProvider
//             attribute="class"
//             defaultTheme="system"
//             enableSystem
//             disableTransitionOnChange
//           >
//             {children}
//           </ThemeProvider>
//       </body>
//     </html>
//   );
// }




import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
// NOTE: ThemeProvider is likely a Client Component managing the theme class on <html>
import { ThemeProvider } from '@/app/context/ThemeContext'; 
import { AuthProvider } from "./context/AuthContext";
import QueryProvider from "./provider/QueryProvider";
import ToastProvider from "@/components/toast";


const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-red-hat-display",
});

export const metadata: Metadata = {
  title: "Whorkaz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // FIX: Apply suppressHydrationWarning to the <html> tag
    // This tells React to ignore attribute mismatches on this element, 
    // which is standard practice when a client-side library like next-themes
    // is responsible for injecting class/style properties on the root element.
    <html lang="en" suppressHydrationWarning> 
      <body className={`${redHatDisplay.className} transition-colors duration-300`}>
        <QueryProvider>
          <AuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ToastProvider />
              {children}
            </ThemeProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
